### ISSUE TITLE
Class Attendence Student UI Implementation

### ISSUE THREAD

**Issue by MohitGupta121** [MohitGupta121/IES-IPS-Andoid#27]
You have to implement the same UI as below in Fragment :- 

![image](https://user-images.githubusercontent.com/76530270/158012039-9b58a303-00b8-45cd-a420-292fc0a7300a.png)

**Comment by ismailbohra** [comment]
i want to work on this task please assign me

**Comment by MohitGupta121** [comment]
> i want to work on this task please assign me

Okay I'll assign u.

**Comment by MohitGupta121** [comment]
@ismailbohra go ahead

**Comment by MohitGupta121** [comment]
Thanks you @ismailbohra  for your PR #36
