### ISSUE TITLE
Implement Tool Bar and Bottom View 

### ISSUE THREAD

**Issue by MohitGupta121** [MohitGupta121/IES-IPS-Andoid#29]
You have to Implement the same Tool Bar with User Name drop-down and calendar session drop-down with footer view:- 

<table role="table">
<thead>
<tr>
<th>Calendar Drop-Down</th>
<th>Profile Drop-Down</th>
</tr>
</thead>
<tbody>
<tr>
<td><img src="https://user-images.githubusercontent.com/76530270/158018645-d562aab2-d62a-4e78-b9af-64d97572094e.png" alt="Screenshot_20210804_152357" style="max-width:100%;"></a></td>
<td><img src="https://user-images.githubusercontent.com/76530270/158018665-34b178ba-63d3-4c66-8e16-edad8660a328.png" alt="Screenshot_20210804_152357" style="max-width:100%;"></a></td>
</tr>
<tr>

**Comment by MohitGupta121** [comment]
@Shashank-1302 u have to work on this issue
please go ahead and report me on this issue.

**Comment by Shashank-1302** [comment]
Ok sir

**Comment by MohitGupta121** [comment]
Ok gohead thanks you

**Comment by MohitGupta121** [comment]
Thanks you for your PR #35
