### ISSUE TITLE
Build a CI/CD pipeline

### ISSUE THREAD

**Issue by itsnitish22** [MohitGupta121/IES-IPS-Andoid#37]
Whenever there is a new update in the codebase, the workflow will trigger and upload the app to the releases section, once all the tests pass.
If you consider this issue, kindly assign me with it.

**Comment by MohitGupta121** [comment]
> Whenever there is a new update in the codebase, the workflow will trigger and upload the app to the releases section, once all the tests pass. If you consider this issue, kindly assign me with it.

Thanks you bro for your interest, but this project is not for all actually only the members for this repo will contribute on that 😊 that's college project.
I think u understand bro.
