### ISSUE TITLE
You have to Implement the ToolBar

### ISSUE THREAD

**Issue by MohitGupta121** [MohitGupta121/IES-IPS-Andoid#41]
You have to Implement the same ToolBar with User Name drop-down and calendar session drop-down:-

Basically you have to add spinner for that:

<table role="table">
<thead>
<tr>
<th>Calendar Drop-Down</th>
<th>Profile Drop-Down</th>
</tr>
</thead>
<tbody>
<tr>
<td><img src="https://user-images.githubusercontent.com/76530270/158018645-d562aab2-d62a-4e78-b9af-64d97572094e.png" alt="Screenshot_20210804_152357" style="max-width:100%;"></a></td>
<td><img src="https://user-images.githubusercontent.com/76530270/158018665-34b178ba-63d3-4c66-8e16-edad8660a328.png" alt="Screenshot_20210804_152357" style="max-width:100%;"></a></td>
</tr>
<tr>

**Comment by MohitGupta121** [comment]
@Shashank-1302 please complete this issue you have to implement drop-down spinner on calendar icon and profile icon from Java-To-Kotlin Branch

**Comment by Shashank-1302** [comment]
Ok

**Comment by MohitGupta121** [comment]
@Shashank-1302 where are u stuck?

**Comment by MohitGupta121** [comment]
@Shashank-1302 are you working on the calender popup ??

**Comment by KeshavAnandBhagat** [comment]
Please assign me this issue under hacktoberfest

**Comment by MohitGupta121** [comment]
@KeshavAnandBhagat Sorry this issue is already fixed
